
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author JohnLuy
 */
public class Home_Page extends javax.swing.JFrame {

    /**
     * Creates new form Home_Page
     */
    public Home_Page() {
        initComponents();
         this.setLocationRelativeTo(null);
    }
    String imgPath =null;
    
    public ImageIcon ResizeImage(String ImagePath, byte[] pic){
        ImageIcon MyImage = null;
        if(ImagePath != null ){
            MyImage = new ImageIcon(ImagePath);
        } else{
            MyImage = new ImageIcon(pic);
        }
        Image img = MyImage.getImage();
        Image newImg = img.getScaledInstance(lbl_Image.getWidth(),lbl_Image.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg);
        return image;
    }
    
    public static Connection getConnection()
    {
        Connection con = null;
        
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/images_db","root","");
            return con;
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null,"not connected");
            return null;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        JSPINNER_ID = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        BTN_SEARCH = new javax.swing.JButton();
        lbl_Image = new javax.swing.JLabel();
        BTN_CHOOSE = new javax.swing.JButton();
        BNT_EDIT = new javax.swing.JButton();
        BNT_ADD = new javax.swing.JButton();
        BNT_REMOVE = new javax.swing.JButton();
        OUT = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        JSPINNER_ID.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel1.setText("ID of picture");

        BTN_SEARCH.setBackground(new java.awt.Color(153, 0, 153));
        BTN_SEARCH.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        BTN_SEARCH.setText("SEARCH");
        BTN_SEARCH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_SEARCHActionPerformed(evt);
            }
        });

        lbl_Image.setBackground(new java.awt.Color(255, 255, 255));
        lbl_Image.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 255), 3));
        lbl_Image.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        BTN_CHOOSE.setBackground(new java.awt.Color(204, 153, 255));
        BTN_CHOOSE.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        BTN_CHOOSE.setText("CHOOSE");
        BTN_CHOOSE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_CHOOSEActionPerformed(evt);
            }
        });

        BNT_EDIT.setBackground(new java.awt.Color(204, 102, 255));
        BNT_EDIT.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        BNT_EDIT.setText("UPDATE");
        BNT_EDIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BNT_EDITActionPerformed(evt);
            }
        });

        BNT_ADD.setBackground(new java.awt.Color(204, 51, 255));
        BNT_ADD.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        BNT_ADD.setText("INSERT");
        BNT_ADD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BNT_ADDActionPerformed(evt);
            }
        });

        BNT_REMOVE.setBackground(new java.awt.Color(204, 0, 204));
        BNT_REMOVE.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        BNT_REMOVE.setText("DELETE");
        BNT_REMOVE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BNT_REMOVEActionPerformed(evt);
            }
        });

        OUT.setBackground(new java.awt.Color(242, 38, 19));
        OUT.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        OUT.setForeground(new java.awt.Color(255, 255, 255));
        OUT.setText("LOG OUT");
        OUT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OUTMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 204));
        jLabel2.setText("BGON! Your Safe of Pictures");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JSPINNER_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BTN_SEARCH, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BTN_CHOOSE, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                            .addComponent(BNT_EDIT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BNT_ADD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BNT_REMOVE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(30, 30, 30)
                        .addComponent(lbl_Image, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(72, 72, 72))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(OUT, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JSPINNER_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTN_SEARCH, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_Image, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(BTN_CHOOSE, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(BNT_EDIT, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(BNT_ADD, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(BNT_REMOVE, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(OUT, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BNT_EDITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BNT_EDITActionPerformed
        // TODO add your handling code here:
       if (imgPath != null) {
            try {
               InputStream img = new FileInputStream(imgPath);
               String UpdateQuery = "UPDATE tbl_images SET the_image= ? WHERE id = ?";
               int id = Integer.parseInt(JSPINNER_ID.getValue().toString());
            PreparedStatement ps = getConnection().prepareStatement(UpdateQuery);
            ps.setBlob(1,img);
            ps.setInt(2, id);
            if(ps.executeUpdate()==1){
                JOptionPane.showMessageDialog(null,"Image Updated");
            }else{
                JOptionPane.showMessageDialog(null,"No Image Exist With This ID");
            }
            } catch (Exception ex) {
                Logger.getLogger(Home_Page.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }else{
           JOptionPane.showMessageDialog(null,"No Image Selected");
       }
       imgPath = null;
    }//GEN-LAST:event_BNT_EDITActionPerformed

    private void BTN_CHOOSEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_CHOOSEActionPerformed
        // TODO add your handling code here:
         JFileChooser file = new JFileChooser();
        file.setCurrentDirectory(new File(System.getProperty("user.home")));
        FileNameExtensionFilter filter = new FileNameExtensionFilter("*.images","jpg","gif","png");
        file.addChoosableFileFilter(filter);
        int result = file.showSaveDialog(null);
        if(result == JFileChooser.APPROVE_OPTION){
            File selectedFile = file.getSelectedFile();
            String path = selectedFile.getAbsolutePath();
            lbl_Image.setIcon(ResizeImage(path,null));
            imgPath = path;
        }else if(result == JFileChooser.CANCEL_OPTION){
            System.out.println("No File Select");
        }
    }//GEN-LAST:event_BTN_CHOOSEActionPerformed

    private void BNT_ADDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BNT_ADDActionPerformed
        // TODO add your handling code here:
        if (imgPath != null ){
            try {
                PreparedStatement ps =getConnection().prepareStatement("INSERT INTO tbl_images(the_image) VALUES (?)");
                InputStream img = new FileInputStream(new File(imgPath));
                ps.setBlob(1, img);
                if(ps.executeUpdate()==1){
                    JOptionPane.showMessageDialog(null,"Image Inserted");
                }
                
            } catch (SQLException ex) {
                Logger.getLogger(Home_Page.class.getName()).log(Level.SEVERE, null, ex);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Home_Page.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
                    JOptionPane.showMessageDialog(null,"Image can not Inserted");
                }
        imgPath = null;
    }//GEN-LAST:event_BNT_ADDActionPerformed

    private void BNT_REMOVEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BNT_REMOVEActionPerformed
        // TODO add your handling code here:
         int id = Integer.parseInt(JSPINNER_ID.getValue().toString());
        String DeleteQuery = "DELETE FROM `tbl_images` WHERE id = ?";
        try {
            PreparedStatement ps = getConnection().prepareStatement(DeleteQuery);
            ps.setInt(1, id);
            if (ps.executeUpdate() == 1) {
                JOptionPane.showMessageDialog(null,"Image Deleted");
            }
            else{
                JOptionPane.showMessageDialog(null,"No Image exist with this ID");
            }
        } catch (SQLException ex) {
            Logger.getLogger(Home_Page.class.getName()).log(Level.SEVERE, null, ex);
        }
        lbl_Image.setIcon(null);
    }//GEN-LAST:event_BNT_REMOVEActionPerformed

    private void BTN_SEARCHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_SEARCHActionPerformed
        // TODO add your handling code here:
         int id = Integer.parseInt(JSPINNER_ID.getValue().toString());
        String SelectQuery = "SELECT * FROM `tbl_images` WHERE id = "+id;
        
        Statement st;
        ResultSet rs;
        try {
            st=getConnection().createStatement();
            rs = st.executeQuery(SelectQuery);
            if (rs.next()) {
                lbl_Image.setIcon(ResizeImage(null,rs.getBytes("The_image")));
                
            }else{
                JOptionPane.showMessageDialog(null,"This Image Can't Found");
            }
        } catch (SQLException ex) {
            Logger.getLogger(Home_Page.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BTN_SEARCHActionPerformed

    private void OUTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OUTMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_OUTMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home_Page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BNT_ADD;
    private javax.swing.JButton BNT_EDIT;
    private javax.swing.JButton BNT_REMOVE;
    private javax.swing.JButton BTN_CHOOSE;
    private javax.swing.JButton BTN_SEARCH;
    private javax.swing.JSpinner JSPINNER_ID;
    private javax.swing.JButton OUT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl_Image;
    // End of variables declaration//GEN-END:variables
}
