/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ql_nhahang;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lamct
 */
public class quanlyForm extends javax.swing.JFrame {
    
    static void main() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    private String ten = "%%";
    private String chungloai = "%%";

    /**
     * Creates new form quanlyForm
     */
    public quanlyForm() {
        initComponents();
    }
    private void lammoi() {
        try{  
        Class.forName("com.mysql.cj.jdbc.Driver");  
        Connection con=DriverManager.getConnection(  
        "jdbc:mysql://localhost:3306/nhahang","root",Ql_nhahang.mysqlpass);  
        //here sonoo is database name, root is username and password  
        Statement stmt=con.createStatement();  
        ResultSet rs=stmt.executeQuery("SELECT id_nv, ten_nv, gioitinh, ngaysinh, sdt, cmnd, quequan FROM nhahang.nhanvien;");
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        //int cout = 0;
        while(rs.next()){
            //System.out.println(rs.getInt(1)+"\t"+rs.getString(2)+"\t"+rs.getString(3)+"\t"+rs.getInt(4)+"\t"+rs.getInt(5)+"\t"+ rs.getString(6)});
            model.addRow(new Object[]{rs.getInt(1),rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5), rs.getString(6), rs.getString(7)});
            //cout = cout + 1;
        }
        //jLabel18.setText("Tổng số: " + String.valueOf(cout));


        con.close();
        }catch(Exception e){ System.out.println(e);}
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane3 = new javax.swing.JTabbedPane();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        buttonGroup8 = new javax.swing.ButtonGroup();
        buttonGroup9 = new javax.swing.ButtonGroup();
        buttonGroup10 = new javax.swing.ButtonGroup();
        buttonGroup11 = new javax.swing.ButtonGroup();
        buttonGroup12 = new javax.swing.ButtonGroup();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel9 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton8 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable6 = new javax.swing.JTable();
        jTextField11 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jTextField8 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(2147483647, 214748364));
        setSize(new java.awt.Dimension(1280, 720));

        jPanel9.setBackground(new java.awt.Color(102, 102, 102));

        jLabel2.setBackground(new java.awt.Color(51, 102, 255));
        jLabel2.setFont(new java.awt.Font("Calibri", 1, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 204, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Restaurant Manager");

        jButton11.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton11.setText("Log Out");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jTabbedPane4.setBackground(new java.awt.Color(204, 204, 204));
        jTabbedPane4.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel1.setText("Staff ID :");

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel3.setText("Name:");

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel4.setText("Gender:");

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel5.setText("Date of Birth:");

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel6.setText("Home Town:");

        jLabel7.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel7.setText("ID card number:");

        jLabel8.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel8.setText("Phone Number:");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jRadioButton1.setText("Male");
        jRadioButton1.setName("Nam"); // NOI18N

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jRadioButton2.setText("Female");
        jRadioButton2.setToolTipText("");
        jRadioButton2.setName("Nữ"); // NOI18N
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Gender", "Birthday", "Phone number", "ID card number", "Home Town"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMaxWidth(55);
        }
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection(
                "jdbc:mysql://localhost:3306/nhahang","root",Ql_nhahang.mysqlpass);
            //here sonoo is database name, root is username and password
            Statement stmt=con.createStatement();
            ResultSet rs=stmt.executeQuery("SELECT id_nv, ten_nv, gioitinh, ngaysinh, sdt, cmnd, quequan FROM nhahang.nhanvien;");
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setRowCount(0);
            //int cout = 0;
            while(rs.next()){
                //System.out.println(rs.getInt(1)+"\t"+rs.getString(2)+"\t"+rs.getString(3)+"\t"+rs.getInt(4)+"\t"+rs.getInt(5)+"\t"+ rs.getString(6)});
            model.addRow(new Object[]{rs.getInt(1),rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5), rs.getString(6), rs.getString(7)});
            //cout = cout + 1;
        }
        //jLabel18.setText("Tổng số: " + String.valueOf(cout));
        //To remove previously added rows

        con.close();
    }catch(Exception e){ System.out.println(e);}

    jButton8.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
    jButton8.setText("Add");
    jButton8.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton8ActionPerformed(evt);
        }
    });

    jButton6.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
    jButton6.setText("Edit");
    jButton6.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton6ActionPerformed(evt);
        }
    });

    jButton7.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
    jButton7.setText("Delete");
    jButton7.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton7ActionPerformed(evt);
        }
    });

    jButton13.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
    jButton13.setText("Refresh");
    jButton13.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton13ActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(35, 35, 35)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4)
                        .addComponent(jLabel5)
                        .addComponent(jLabel8)
                        .addComponent(jLabel7)
                        .addComponent(jLabel6)
                        .addComponent(jLabel1))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField7)
                            .addComponent(jTextField6)
                            .addComponent(jTextField5)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jRadioButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton2)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jTextField2)
                            .addComponent(jTextField4)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 930, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(23, 23, 23)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jButton13))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addContainerGap())
    );
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(49, 49, 49)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jRadioButton1)
                .addComponent(jRadioButton2))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(13, 13, 13)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(35, 35, 35)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(137, Short.MAX_VALUE))
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jScrollPane1)
            .addContainerGap())
    );

    jTabbedPane4.addTab("Employee Manager", jPanel1);

    jTable3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    jTable3.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {

        },
        new String [] {
            "ID", "User", "T2", "T3", "T4", "T5", "T6", "T7", "CN"
        }
    ) {
        Class[] types = new Class [] {
            java.lang.String.class, java.lang.String.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class
        };
        boolean[] canEdit = new boolean [] {
            false, false, true, true, true, true, true, true, true
        };

        public Class getColumnClass(int columnIndex) {
            return types [columnIndex];
        }

        public boolean isCellEditable(int rowIndex, int columnIndex) {
            return canEdit [columnIndex];
        }
    });
    jScrollPane3.setViewportView(jTable3);
    if (jTable3.getColumnModel().getColumnCount() > 0) {
        jTable3.getColumnModel().getColumn(0).setMaxWidth(60);
        jTable3.getColumnModel().getColumn(2).setMaxWidth(55);
        jTable3.getColumnModel().getColumn(3).setMaxWidth(55);
        jTable3.getColumnModel().getColumn(4).setMaxWidth(55);
        jTable3.getColumnModel().getColumn(5).setMaxWidth(55);
        jTable3.getColumnModel().getColumn(6).setMaxWidth(55);
        jTable3.getColumnModel().getColumn(7).setMaxWidth(55);
        jTable3.getColumnModel().getColumn(8).setMaxWidth(55);
    }
    try{
        Class.forName("com.mysql.jdbc.Driver");
        Connection con=DriverManager.getConnection(
            "jdbc:mysql://localhost:3306/nhahang","root",Ql_nhahang.mysqlpass);
        //here sonoo is database name, root is username and password
        Statement stmt=con.createStatement();
        ResultSet rs=stmt.executeQuery("SELECT id_nv ,ten_nv, t2, t3, t4,t5,t6,t7,cn FROM nhahang.nhanvien;");
        DefaultTableModel model = (DefaultTableModel) jTable3.getModel();
        model.setRowCount(0);
        //int cout = 0;
        while(rs.next()){
            //System.out.println(rs.getInt(1)+"\t"+rs.getString(2)+"\t"+rs.getString(3)+"\t"+rs.getInt(4)+"\t"+rs.getInt(5)+"\t"+ rs.getString(6)});
        model.addRow(new Object[]{rs.getString(1),rs.getString(2), rs.getBoolean(3), rs.getBoolean(4), rs.getBoolean(5), rs.getBoolean(6), rs.getBoolean(7), rs.getBoolean(8), rs.getBoolean(9)});
        //cout = cout + 1;
    }
    //jLabel18.setText("Tổng số: " + String.valueOf(cout));
    //To remove previously added rows

    con.close();
    }catch(Exception e){ System.out.println(e);}

    jButton1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
    jButton1.setText("search");
    jButton1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton1ActionPerformed(evt);
        }
    });

    jButton2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
    jButton2.setText("OK");
    jButton2.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton2ActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel2Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 1245, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(38, 38, 38)
                    .addComponent(jButton1)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2)))
            .addContainerGap())
    );
    jPanel2Layout.setVerticalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jButton1)
                .addComponent(jButton2))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap())
    );

    jTabbedPane4.addTab("Schedule", jPanel2);

    jTable6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    jTable6.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {

        },
        new String [] {
            "ID", "Password", "User "
        }
    ) {
        Class[] types = new Class [] {
            java.lang.String.class, java.lang.String.class, java.lang.Object.class
        };
        boolean[] canEdit = new boolean [] {
            false, false, false
        };

        public Class getColumnClass(int columnIndex) {
            return types [columnIndex];
        }

        public boolean isCellEditable(int rowIndex, int columnIndex) {
            return canEdit [columnIndex];
        }
    });
    jScrollPane6.setViewportView(jTable6);
    try{
        Class.forName("com.mysql.jdbc.Driver");
        Connection con=DriverManager.getConnection(
            "jdbc:mysql://localhost:3306/nhahang","root",Ql_nhahang.mysqlpass);
        //here sonoo is database name, root is username and password
        Statement stmt=con.createStatement();
        ResultSet rs=stmt.executeQuery("SELECT distinct login.tendangnhap, login.matkhau, nhanvien.ten_nv FROM nhahang.login join nhahang.nhanvien where nhanvien.tendangnhap = login.tendangnhap;");
        DefaultTableModel model = (DefaultTableModel) jTable6.getModel();
        model.setRowCount(0);
        //int cout = 0;
        while(rs.next()){
            //System.out.println(rs.getInt(1)+"\t"+rs.getString(2)+"\t"+rs.getString(3)+"\t"+rs.getInt(4)+"\t"+rs.getInt(5));
            model.addRow(new Object[]{rs.getString(1),rs.getString(2), rs.getString(3)});
            //cout = cout + 1;
        }
        //jLabel18.setText("Tổng số: " + String.valueOf(cout));
        //To remove previously added rows

        con.close();
    }catch(Exception e){ System.out.println(e);}

    jTextField11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

    jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
    jLabel17.setText("User Name:");

    jLabel18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
    jLabel18.setText("Password:");

    jTextField12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

    jButton9.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
    jButton9.setText("Add");
    jButton9.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton9ActionPerformed(evt);
        }
    });

    jButton10.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
    jButton10.setText("Delete");
    jButton10.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton10ActionPerformed(evt);
        }
    });

    jLabel21.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
    jLabel21.setText("User:");

    jComboBox4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
    jComboBox4.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jComboBox4ActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
    jPanel4.setLayout(jPanel4Layout);
    jPanel4Layout.setHorizontalGroup(
        jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel4Layout.createSequentialGroup()
            .addGap(29, 29, 29)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addComponent(jButton9)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                    .addComponent(jButton10))
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel17)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel21)
                            .addComponent(jLabel18)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextField12, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                        .addComponent(jTextField11)
                        .addComponent(jComboBox4, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGap(205, 205, 205)
            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 855, javax.swing.GroupLayout.PREFERRED_SIZE))
    );
    jPanel4Layout.setVerticalGroup(
        jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
            .addGap(23, 23, 23)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel17))
            .addGap(18, 18, 18)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel18))
            .addGap(18, 18, 18)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel21)
                .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jButton9)
                .addComponent(jButton10))
            .addGap(303, 303, 303))
        .addGroup(jPanel4Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jScrollPane6))
    );

    try{
        Class.forName("com.mysql.jdbc.Driver");
        Connection con=DriverManager.getConnection(
            "jdbc:mysql://localhost:3306/nhahang","root",Ql_nhahang.mysqlpass);
        //here sonoo is database name, root is username and password
        Statement stmt=con.createStatement();
        ResultSet rs=stmt.executeQuery("SELECT ten_nv , tendangnhap FROM nhahang.nhanvien where tendangnhap is NULL;");
        DefaultComboBoxModel model = (DefaultComboBoxModel) jComboBox4.getModel();
        //int cout = 0;
        while(rs.next()){
            model.addElement(rs.getString(1));
        }

        con.close();
    }catch(Exception e){ System.out.println(e);}

    jTabbedPane4.addTab("User's account", jPanel4);

    jTable5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    jTable5.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {

        },
        new String [] {
            "ID", "Name", "he so luong", "Week's salary"
        }
    ) {
        Class[] types = new Class [] {
            java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
        };
        boolean[] canEdit = new boolean [] {
            false, false, true, false
        };

        public Class getColumnClass(int columnIndex) {
            return types [columnIndex];
        }

        public boolean isCellEditable(int rowIndex, int columnIndex) {
            return canEdit [columnIndex];
        }
    });
    jScrollPane5.setViewportView(jTable5);
    if (jTable5.getColumnModel().getColumnCount() > 0) {
        jTable5.getColumnModel().getColumn(1).setResizable(false);
    }
    try{
        Class.forName("com.mysql.jdbc.Driver");
        Connection con=DriverManager.getConnection(
            "jdbc:mysql://localhost:3306/nhahang","root",Ql_nhahang.mysqlpass);
        //here sonoo is database name, root is username and password
        Statement stmt=con.createStatement();
        ResultSet rs=stmt.executeQuery("select id_nv, ten_nv, hesoluong, (t2+t3+t4+t5+t6+t7+cn)*hesoluong from nhanvien;");
        DefaultTableModel model = (DefaultTableModel) jTable5.getModel();
        model.setRowCount(0);
        int lcb = 100000;
        //System.out.println(lcb);
        int sum = 0;
        while(rs.next()){
            System.out.println(rs.getInt(1)+"\t"+rs.getString(2)+"\t"+rs.getString(3)+"\t"+rs.getInt(4));
            model.addRow(new Object[]{rs.getInt(1),rs.getString(2), rs.getInt(3), rs.getInt(4)*lcb});
            sum = sum + rs.getInt(4)*lcb;
        }
        jLabel16.setText("Tổng phải trả: " + String.valueOf(sum) + " Đồng");
        //To remove previously added rows

        con.close();
    }catch(Exception e){ System.out.println(e);}

    jButton5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
    jButton5.setText("Update");
    jButton5.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton5ActionPerformed(evt);
        }
    });

    jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
    jLabel15.setText("Basic Salary ( days) :");

    jTextField10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
    jTextField10.setText("100000");
    jTextField10.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jTextField10ActionPerformed(evt);
        }
    });

    jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

    javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
    jPanel5.setLayout(jPanel5Layout);
    jPanel5Layout.setHorizontalGroup(
        jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel5Layout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 1198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton5)
                        .addGap(45, 45, 45)))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                    .addComponent(jLabel16)
                    .addGap(344, 344, 344))))
    );
    jPanel5Layout.setVerticalGroup(
        jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
            .addGap(31, 31, 31)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jButton5)
                .addComponent(jLabel15)
                .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(34, 34, 34)
            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(23, 23, 23))
    );

    System.out.println(jTextField10.getText());

    jTabbedPane4.addTab("Salary", jPanel5);

    jTable4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    jTable4.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {

        },
        new String [] {
            "ID", "Tên mặt hàng", "Chủng loại", "Đơn giá", "Số lượng"
        }
    ) {
        Class[] types = new Class [] {
            java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
        };
        boolean[] canEdit = new boolean [] {
            false, true, true, false, true
        };

        public Class getColumnClass(int columnIndex) {
            return types [columnIndex];
        }

        public boolean isCellEditable(int rowIndex, int columnIndex) {
            return canEdit [columnIndex];
        }
    });
    jTable4.setRowHeight(24);
    jScrollPane4.setViewportView(jTable4);
    try{
        Class.forName("com.mysql.jdbc.Driver");
        Connection con=DriverManager.getConnection(
            "jdbc:mysql://localhost:3306/nhahang","root",Ql_nhahang.mysqlpass);
        //here sonoo is database name, root is username and password
        Statement stmt=con.createStatement();
        ResultSet rs=stmt.executeQuery("select * from mathang");
        DefaultTableModel model = (DefaultTableModel) jTable4.getModel();
        model.setRowCount(0);
        int cout = 0;
        while(rs.next()){
            //System.out.println(rs.getInt(1)+"\t"+rs.getString(2)+"\t"+rs.getString(3)+"\t"+rs.getInt(4)+"\t"+rs.getInt(5));
            model.addRow(new Object[]{rs.getInt(1),rs.getString(2), rs.getString(3), rs.getInt(4), rs.getInt(5)});
            cout = cout + 1;
        }
        jLabel11.setText("Tổng số: " + String.valueOf(cout));
        //To remove previously added rows

        con.close();
    }catch(Exception e){ System.out.println(e);}

    jButton3.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
    jButton3.setText("Search");
    jButton3.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton3ActionPerformed(evt);
        }
    });

    jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Đồ ăn", "Đồ uống", "Khác" }));
    jComboBox3.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jComboBox3ActionPerformed(evt);
        }
    });

    jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

    jLabel12.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
    jLabel12.setText("Species:");

    jButton4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
    jButton4.setText("OK");
    jButton4.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton4ActionPerformed(evt);
        }
    });

    jLabel13.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
    jLabel13.setText("Total + ");

    jLabel14.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
    jLabel14.setText("VND");

    javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
    jPanel3.setLayout(jPanel3Layout);
    jPanel3Layout.setHorizontalGroup(
        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel3Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane4)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel11)
                            .addGap(0, 0, Short.MAX_VALUE)))
                    .addContainerGap())
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(26, 26, 26)
                            .addComponent(jButton3))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel12)
                            .addGap(37, 37, 37)
                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(125, 125, 125)
                    .addComponent(jLabel13)
                    .addGap(18, 18, 18)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(jLabel14)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 480, Short.MAX_VALUE)
                    .addComponent(jButton4)
                    .addGap(55, 55, 55))))
    );
    jPanel3Layout.setVerticalGroup(
        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel3Layout.createSequentialGroup()
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(37, 37, 37)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton3))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12)
                        .addComponent(jLabel13)
                        .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel14)))
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(59, 59, 59)
                    .addComponent(jButton4)))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE))
    );

    jTabbedPane4.addTab("Foods Update", jPanel3);

    jTable2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    jTable2.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {

        },
        new String [] {
            "ID mặt hàng", "Tên mặt hàng", "Đơn giá", "Số lượng đã bán", "Doanh thu"
        }
    ) {
        Class[] types = new Class [] {
            java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
        };
        boolean[] canEdit = new boolean [] {
            false, false, false, false, false
        };

        public Class getColumnClass(int columnIndex) {
            return types [columnIndex];
        }

        public boolean isCellEditable(int rowIndex, int columnIndex) {
            return canEdit [columnIndex];
        }
    });
    jScrollPane2.setViewportView(jTable2);
    try{
        Class.forName("com.mysql.jdbc.Driver");
        Connection con=DriverManager.getConnection(
            "jdbc:mysql://localhost:3306/nhahang","root",Ql_nhahang.mysqlpass);
        //here sonoo is database name, root is username and password
        Statement stmt=con.createStatement();
        ResultSet rs=stmt.executeQuery("SELECT distinct mathang.id_hang, mathang.tenmathang, mathang.gia, sum(chitiethoadon.soluong) as soluong, sum(mathang.gia * chitiethoadon.soluong) as doanhthu\n" +
            "FROM chitiethoadon join mathang join laphoadon\n" +
            "where mathang.id_hang = chitiethoadon.id_hang \n" +
            "	and chitiethoadon.id_hoadon = laphoadon.id_hoadon \n" +
            "group by mathang.id_hang;");
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        model.setRowCount(0);
        //int cout = 0;
        int tongtien = 0;
        int tongsoluong = 0;
        while(rs.next()){
            //System.out.println(rs.getInt(1)+"\t"+rs.getString(2)+"\t"+rs.getString(3)+"\t"+rs.getInt(4)+"\t"+rs.getInt(5)+"\t"+ rs.getString(6)});
        model.addRow(new Object[]{rs.getInt(1),rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5)});
        //cout = cout + 1;
        tongsoluong += Integer.parseInt(rs.getString(4));
        tongtien += Integer.parseInt(rs.getString(5));
    }
    //jLabel18.setText("Tổng số: " + String.valueOf(cout));

    String t9 = "Tổng tiền: " + String.valueOf(tongtien);
    String t10 = "Tổng số lượng: " + String.valueOf(tongsoluong);
    jLabel10.setText(t10);
    jLabel9.setText(t9);

    con.close();
    }catch(Exception e){ System.out.println(e);}

    jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
    jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Ngày hôm nay", "Tuần này", "Tháng này", "Năm nay" }));
    jComboBox1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jComboBox1ActionPerformed(evt);
        }
    });

    jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

    jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

    javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
    jPanel7.setLayout(jPanel7Layout);
    jPanel7Layout.setHorizontalGroup(
        jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel7Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane2)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                    .addGap(0, 647, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addContainerGap())
    );
    jPanel7Layout.setVerticalGroup(
        jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel7Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel9)
                .addComponent(jLabel10))
            .addContainerGap())
    );

    jTabbedPane4.addTab("Sales Report", jPanel7);

    jLabel19.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 48)); // NOI18N
    jLabel19.setText("Contact:0971437005");

    jLabel20.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 48)); // NOI18N
    jLabel20.setText("email:namkhanh2903@gmail.com");

    javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
    jPanel6.setLayout(jPanel6Layout);
    jPanel6Layout.setHorizontalGroup(
        jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel6Layout.createSequentialGroup()
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(324, 324, 324)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 595, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(179, 179, 179)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 885, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addContainerGap(205, Short.MAX_VALUE))
    );
    jPanel6Layout.setVerticalGroup(
        jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel6Layout.createSequentialGroup()
            .addGap(177, 177, 177)
            .addComponent(jLabel19)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel20)
            .addContainerGap(250, Short.MAX_VALUE))
    );

    jTabbedPane4.addTab("Help", jPanel6);

    javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
    jPanel9.setLayout(jPanel9Layout);
    jPanel9Layout.setHorizontalGroup(
        jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(401, 401, 401)
            .addComponent(jButton11)
            .addGap(51, 51, 51))
        .addComponent(jTabbedPane4)
    );
    jPanel9Layout.setVerticalGroup(
        jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel9Layout.createSequentialGroup()
            .addGap(20, 20, 20)
            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jTabbedPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 571, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addComponent(jSeparator1)
            .addGap(1089, 1089, 1089))
        .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        String querry = "SELECT distinct mathang.id_hang, mathang.tenmathang, mathang.gia, sum(chitiethoadon.soluong) as soluong, sum(mathang.gia * chitiethoadon.soluong) as doanhthu\n" +
        "FROM chitiethoadon join mathang join laphoadon\n" +
        "where mathang.id_hang = chitiethoadon.id_hang \n" +
        "	and chitiethoadon.id_hoadon = laphoadon.id_hoadon \n" +
        "group by mathang.id_hang;";
        String selected = (String) jComboBox1.getSelectedItem();
        switch (selected) {
            case "All":
            querry = "SELECT distinct mathang.id_hang, mathang.tenmathang, mathang.gia, sum(chitiethoadon.soluong) as soluong, sum(mathang.gia * chitiethoadon.soluong) as doanhthu\n" +
            "FROM chitiethoadon join mathang join laphoadon\n" +
            "where mathang.id_hang = chitiethoadon.id_hang \n" +
            "	and chitiethoadon.id_hoadon = laphoadon.id_hoadon \n" +
            "group by mathang.id_hang;";
            break;
            case "Ngày hôm nay":
            querry = "SELECT distinct mathang.id_hang, mathang.tenmathang, mathang.gia, sum(chitiethoadon.soluong) as soluong, sum(mathang.gia * chitiethoadon.soluong) as doanhthu\n" +
            "FROM chitiethoadon join mathang join laphoadon\n" +
            "where mathang.id_hang = chitiethoadon.id_hang \n" +
            "	and chitiethoadon.id_hoadon = laphoadon.id_hoadon \n" +
            "	and date(laphoadon.thoigianlap) = curdate()\n" +
            "group by mathang.id_hang;";
            break;
            case "Tuần này":
            querry = "SELECT distinct mathang.id_hang, mathang.tenmathang, mathang.gia, sum(chitiethoadon.soluong) as soluong, sum(mathang.gia * chitiethoadon.soluong) as doanhthu\n" +
            "FROM chitiethoadon join mathang join laphoadon\n" +
            "\n" +
            "where mathang.id_hang = chitiethoadon.id_hang \n" +
            "	 and chitiethoadon.id_hoadon = laphoadon.id_hoadon \n" +
            "	 and week(laphoadon.thoigianlap) = week(curdate()) and year(laphoadon.thoigianlap) = year(curdate())\n" +
            "group by mathang.id_hang;";
            break;
            case "Tháng này":
            querry = "SELECT distinct mathang.id_hang, mathang.tenmathang, mathang.gia, sum(chitiethoadon.soluong) as soluong, sum(mathang.gia * chitiethoadon.soluong) as doanhthu\n" +
            "FROM chitiethoadon join mathang join laphoadon\n" +
            "\n" +
            "where mathang.id_hang = chitiethoadon.id_hang \n" +
            "	 and chitiethoadon.id_hoadon = laphoadon.id_hoadon \n" +
            "	 and month(laphoadon.thoigianlap) = month(curdate()) and year(laphoadon.thoigianlap) = year(curdate())\n" +
            "group by mathang.id_hang;";
            break;
            case "Năm nay":
            querry = "SELECT distinct mathang.id_hang, mathang.tenmathang, mathang.gia, sum(chitiethoadon.soluong) as soluong, sum(mathang.gia * chitiethoadon.soluong) as doanhthu\n" +
            "FROM chitiethoadon join mathang join laphoadon\n" +
            "where mathang.id_hang = chitiethoadon.id_hang \n" +
            "	and chitiethoadon.id_hoadon = laphoadon.id_hoadon \n" +
            "	and year(laphoadon.thoigianlap) = year(curdate())\n" +
            "group by mathang.id_hang;";
            break;
        }
        lammoitb(querry);
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            //here sonoo is database name, root is username and password
            try (Connection con = DriverManager.getConnection(
                "jdbc:mysql://localhost:3306/nhahang","root",Ql_nhahang.mysqlpass)) {
            //here sonoo is database name, root is username and password
            Statement stmt=con.createStatement();
            ResultSet rs=stmt.executeQuery("SELECT id_nv, ten_nv, gioitinh, ngaysinh, sdt, cmnd, quequan FROM nhahang.nhanvien;");
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setRowCount(0);
            //int cout = 0;
            while(rs.next()){
                //System.out.println(rs.getInt(1)+"\t"+rs.getString(2)+"\t"+rs.getString(3)+"\t"+rs.getInt(4)+"\t"+rs.getInt(5)+"\t"+ rs.getString(6)});
            model.addRow(new Object[]{rs.getInt(1),rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5), rs.getString(6), rs.getString(7)});
            //cout = cout + 1;
        }
        //jLabel18.setText("Tổng số: " + String.valueOf(cout));
        //To remove previously added rows
        }
        }catch(ClassNotFoundException | SQLException e){ System.out.println(e);}

    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        String idnv = jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString();
        xoanv(idnv);
        lammoi();
        lammoilichlm();
        lammoitluong();
        lammoingsd();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        String id_nv = jTextField1.getText();
        String ten_nv = jTextField2.getText();
        String gioitinh = null;
        String ngaysinh = jTextField4.getText();
        String quequan = jTextField7.getText();
        String cmnd = jTextField6.getText();
        String sdt = jTextField5.getText();
        if (jRadioButton1.isSelected()){
            gioitinh = jRadioButton1.getName();
        }
        if (jRadioButton2.isSelected()){
            gioitinh = jRadioButton2.getName();
        }
        System.out.println(gioitinh);
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            try (Connection con = DriverManager.getConnection(
                "jdbc:mysql://localhost:3306/nhahang","root",Ql_nhahang.mysqlpass)) {
            //here sonoo is database name, root is username and password
            Statement stmt=con.createStatement();
            String querry = String.format("INSERT INTO `nhahang`.`nhanvien` (`id_nv`, `ten_nv`, `gioitinh`, `ngaysinh`, `quequan`, `cmnd`, `sdt`) VALUES ('%s', '%s', '%s', '%s', '%s', '%s', '%s');",id_nv,ten_nv,gioitinh,ngaysinh,quequan, cmnd, sdt);
            stmt.executeUpdate(querry);
            JOptionPane.showMessageDialog(rootPane, "Done!!!");
            con.close();
        }
        }
        catch(ClassNotFoundException | SQLException e){
            System.out.println(e);
            JOptionPane.showMessageDialog(rootPane, "error!!!");
        }
        lammoi();
        lammoi();
        lammoilichlm();
        lammoitluong();
        lammoingsd();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        for (int i = 0; i < jTable3.getRowCount(); i ++) {
            int t2 = boolToInt(jTable3.getModel().getValueAt(i, 2).toString());
            int t3 = boolToInt(jTable3.getModel().getValueAt(i, 3).toString());
            int t4 = boolToInt(jTable3.getModel().getValueAt(i, 4).toString());
            int t5 = boolToInt(jTable3.getModel().getValueAt(i, 5).toString());
            int t6 = boolToInt(jTable3.getModel().getValueAt(i, 6).toString());
            int t7 = boolToInt(jTable3.getModel().getValueAt(i, 7).toString());
            int cn = boolToInt(jTable3.getModel().getValueAt(i, 8).toString());
            String id = jTable3.getModel().getValueAt(i, 0).toString();
            updatelichlv(t2,t3,t4,t5,t6,t7,cn,id);
        }
        lammoilichlm();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
            try{  
                Class.forName("com.mysql.cj.jdbc.Driver");  
                Connection con=DriverManager.getConnection(  
                "jdbc:mysql://localhost:3306/nhahang","root",Ql_nhahang.mysqlpass);  
                //here sonoo is database name, root is username and password  
                Statement stmt=con.createStatement();
                String keys = "%" + jTextField3.getText() + "%";
                
                String querry = String.format("SELECT id_nv ,ten_nv, t2, t3, t4,t5,t6,t7,cn FROM nhahang.nhanvien where ten_nv like '%s'", keys);
                ResultSet rs=stmt.executeQuery(querry);
                DefaultTableModel model = (DefaultTableModel) jTable3.getModel();
                model.setRowCount(0);
                //int cout = 0;
                while(rs.next()){
                    //System.out.println(rs.getInt(1)+"\t"+rs.getString(2)+"\t"+rs.getString(3)+"\t"+rs.getInt(4)+"\t"+rs.getInt(5)+"\t"+ rs.getString(6)});
                    model.addRow(new Object[]{rs.getString(1),rs.getString(2), rs.getBoolean(3), rs.getBoolean(4), rs.getBoolean(5), rs.getBoolean(6), rs.getBoolean(7), rs.getBoolean(8), rs.getBoolean(9)});
                    //cout = cout + 1;
                }
                //jLabel18.setText("Tổng số: " + String.valueOf(cout));
        //To remove previously added rows

                con.close();
            }catch(Exception e){ System.out.println(e);}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
        String selected = (String) jComboBox3.getSelectedItem();
        switch (selected) {
            case "All":
                chungloai = "%%";
                break;
            case "Đồ ăn":
                chungloai = "Đồ ăn";
                break;
            case "Đồ uống":
                chungloai = "Đồ uống";
                break;
            case "Khác":
                chungloai = "Khác";
                break;
        }
        //System.out.println(chungloai);
        ten = jTextField8.getText();
        lammoitb(chungloai, "%"+ten+"%");
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String selected = (String) jComboBox3.getSelectedItem();
        switch (selected) {
            case "All":
                chungloai = "%%";
                break;
            case "Đồ ăn":
                chungloai = "Đồ ăn";
                break;
            case "Đồ uống":
                chungloai = "Đồ uống";
                break;
            case "Khác":
                chungloai = "Khác";
                break;
        }
        ten = jTextField8.getText();
        //System.out.println(ten);
        lammoitb(chungloai, "%"+ten+"%");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String tatca = jTextField9.getText();
        System.err.println(tatca);
        for (int i = 0; i < jTable4.getRowCount(); i++) {
            String idmh = jTable4.getModel().getValueAt(i, 0).toString();
            updategia(idmh,tatca);
        }
        lammoitb(chungloai, "%"+ten+"%");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        for (int i = 0; i < jTable1.getRowCount(); i++) {
            int hsl = (int) jTable5.getModel().getValueAt(i, 2);
            int id = (int) jTable5.getModel().getValueAt(i, 0);
            updatehsl(id , hsl);
            }
        lammoitluong();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        int column = 0;
        int row = jTable6.getSelectedRow();
        String tentk;
        tentk = jTable6.getValueAt(row,column).toString();
        xoatk(tentk);
        lammoitbphanquyen();
        lammoingsd();
        
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        String tentk = jTextField11.getText();
        String matkhau = jTextField12.getText();
        String tenngd = jComboBox4.getSelectedItem().toString();
        themtkng(tentk,matkhau,tenngd);
        lammoitbphanquyen();
        lammoingsd();
        
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        String[] args = null;
        // TODO add your handling code here:
        dangnhap.main(args);
        dispose();
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(quanlyForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new quanlyForm().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup10;
    private javax.swing.ButtonGroup buttonGroup11;
    private javax.swing.ButtonGroup buttonGroup12;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.ButtonGroup buttonGroup8;
    private javax.swing.ButtonGroup buttonGroup9;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private static javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable5;
    private javax.swing.JTable jTable6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
    private void lammoitb(String querry) {
        try{  
            Class.forName("com.mysql.cj.jdbc.Driver");  
            Connection con=DriverManager.getConnection(  
            "jdbc:mysql://localhost:3306/nhahang","root",Ql_nhahang.mysqlpass);  
            //here sonoo is database name, root is username and password  
            Statement stmt=con.createStatement();
            ResultSet rs=stmt.executeQuery(querry);
            DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
            model.setRowCount(0);
            //int cout = 0;
            int tongtien = 0;
            int tongsoluong = 0;
            while(rs.next()){
                //System.out.println(rs.getInt(1)+"\t"+rs.getString(2)+"\t"+rs.getString(3)+"\t"+rs.getInt(4)+"\t"+rs.getInt(5)+"\t"+ rs.getString(6)});
                model.addRow(new Object[]{rs.getInt(1),rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5)});
                //cout = cout + 1;
                tongsoluong += Integer.parseInt(rs.getString(4));
                tongtien += Integer.parseInt(rs.getString(5));
            }
            //jLabel18.setText("Tổng số: " + String.valueOf(cout));

            String t9 = "Tổng tiền: " + String.valueOf(tongtien);
            String t10 = "Tổng số lượng: " + String.valueOf(tongsoluong);
            jLabel10.setText(t10);
            jLabel9.setText(t9);

            con.close();
        }catch(Exception e){ System.out.println(e);}

    }
    private void lammoilichlm() {
        try{  
            Class.forName("com.mysql.cj.jdbc.Driver");  
            Connection con=DriverManager.getConnection(  
            "jdbc:mysql://localhost:3306/nhahang","root",Ql_nhahang.mysqlpass);  
            //here sonoo is database name, root is username and password  
            Statement stmt=con.createStatement();  
            ResultSet rs=stmt.executeQuery("SELECT id_nv ,ten_nv, t2, t3, t4,t5,t6,t7,cn FROM nhahang.nhanvien;");
            DefaultTableModel model = (DefaultTableModel) jTable3.getModel();
            model.setRowCount(0);
            //int cout = 0;
            while(rs.next()){
                //System.out.println(rs.getInt(1)+"\t"+rs.getString(2)+"\t"+rs.getString(3)+"\t"+rs.getInt(4)+"\t"+rs.getInt(5)+"\t"+ rs.getString(6)});
                model.addRow(new Object[]{rs.getString(1),rs.getString(2), rs.getBoolean(3), rs.getBoolean(4), rs.getBoolean(5), rs.getBoolean(6), rs.getBoolean(7), rs.getBoolean(8), rs.getBoolean(9)});
                //cout = cout + 1;
            }
            //jLabel18.setText("Tổng số: " + String.valueOf(cout));
    //To remove previously added rows

            con.close();
        }catch(Exception e){ System.out.println(e);}
    }
    
    private void updatelichlv(int t2, int t3, int t4, int t5, int t6, int t7, int cn, String id) {
        try{  
            Class.forName("com.mysql.cj.jdbc.Driver");  
            Connection con=DriverManager.getConnection(  
            "jdbc:mysql://localhost:3306/nhahang","root",Ql_nhahang.mysqlpass);  
            //here sonoo is database name, root is username and password  
            Statement stmt=con.createStatement();
            String querry;
            querry = String.format("UPDATE `nhahang`.`nhanvien` SET `t2` = '%d', `t3` = '%d', `t4` = '%d', `t5` = '%d', `t6` = '%d', `t7` = '%d', `cn` = '%d' WHERE (`id_nv` = '%s');", t2,t3,t4,t5,t6,t7,cn,id);
            System.err.println(querry);
            stmt.executeUpdate(querry);

            con.close();
        }catch(Exception e){ System.out.println(e);}
    }
    private int boolToInt(String b) {
        if ("true".equals(b)) {return 1;}
            else return 0;
    }

    private void lammoitb(String chungloai, String ten) {
        try{  
            Class.forName("com.mysql.cj.jdbc.Driver");  
            Connection con=DriverManager.getConnection(  
            "jdbc:mysql://localhost:3306/nhahang","root",Ql_nhahang.mysqlpass);  
            //here sonoo is database name, root is username and password  
            Statement stmt=con.createStatement();
            String querry = String.format("select * from mathang where tenmathang like '%s' and chungloai like '%s';",ten,chungloai);
            System.err.println(querry);
            ResultSet rs=stmt.executeQuery(querry);
            DefaultTableModel model = (DefaultTableModel) jTable4.getModel();
            model.setRowCount(0);
            int cout = 0;
            while(rs.next()){
                //System.out.println(rs.getInt(1)+"\t"+rs.getString(2)+"\t"+rs.getString(3)+"\t"+rs.getInt(4)+"\t"+rs.getInt(5));
                model.addRow(new Object[]{rs.getInt(1),rs.getString(2), rs.getString(3), rs.getInt(4), rs.getInt(5)});
                cout = cout + 1;
            }
            jLabel11.setText("Tổng số: " + String.valueOf(cout));
//To remove previously added rows
            con.close();
        }catch(Exception e){ System.out.println(e);}
    }

    private void updategia(String id, String dongia) {
        try{  
            Class.forName("com.mysql.cj.jdbc.Driver");  
            Connection con=DriverManager.getConnection(  
            "jdbc:mysql://localhost:3306/nhahang","root",Ql_nhahang.mysqlpass);  
            //here sonoo is database name, root is username and password  
            Statement stmt=con.createStatement();
            String querry = String.format("UPDATE `nhahang`.`mathang` SET `gia` = `gia` + %s WHERE (`id_hang` = '%s');",dongia,id);
            System.err.println(querry);
            stmt.executeUpdate(querry);
            
//To remove previously added rows
            con.close();
        }catch(Exception e){ System.out.println(e);}
        
    }

    private void updatehsl(int id, int hsl) {
        try{  
            Class.forName("com.mysql.cj.jdbc.Driver");  
            Connection con=DriverManager.getConnection(  
            "jdbc:mysql://localhost:3306/nhahang","root",Ql_nhahang.mysqlpass);  
            //here sonoo is database name, root is username and password  
            Statement stmt=con.createStatement();
            String querry = String.format("UPDATE `nhahang`.`nhanvien` SET `hesoluong` = '%d' WHERE (`id_nv` = '%d');",hsl,id);
            System.err.println(querry);
            stmt.executeUpdate(querry);
            
//To remove previously added rows
            con.close();
        }catch(Exception e){ System.out.println(e);}
    }

    private void lammoitluong() {
        try{  
            Class.forName("com.mysql.cj.jdbc.Driver");  
            Connection con=DriverManager.getConnection(  
            "jdbc:mysql://localhost:3306/nhahang","root",Ql_nhahang.mysqlpass);  
            //here sonoo is database name, root is username and password  
            Statement stmt=con.createStatement();  
            ResultSet rs=stmt.executeQuery("select id_nv, ten_nv, hesoluong, (t2+t3+t4+t5+t6+t7+cn)*hesoluong from nhanvien;");
            DefaultTableModel model = (DefaultTableModel) jTable5.getModel();
            model.setRowCount(0);
            int lcb = Integer.parseInt(jTextField10.getText());
            //System.out.println(lcb);
            int sum = 0;
            while(rs.next()){
                System.out.println(rs.getInt(1)+"\t"+rs.getString(2)+"\t"+rs.getString(3)+"\t"+rs.getInt(4));
                model.addRow(new Object[]{rs.getInt(1),rs.getString(2), rs.getInt(3), rs.getInt(4)*lcb});
                sum = sum + rs.getInt(4)*lcb;
            }
            jLabel16.setText("Tổng phải trả: " + String.valueOf(sum) + " Đồng");
//To remove previously added rows
            
            con.close();
        }catch(Exception e){ System.out.println(e);}
    }

    private void xoatk(String tentk) {
        try{  
            Class.forName("com.mysql.cj.jdbc.Driver");  
            Connection con=DriverManager.getConnection(  
            "jdbc:mysql://localhost:3306/nhahang","root",Ql_nhahang.mysqlpass);  
            //here sonoo is database name, root is username and password  
            Statement stmt=con.createStatement();
            String querry = String.format("DELETE FROM `nhahang`.`login` WHERE (`tendangnhap` = '%s');",tentk);
            String querry0 = String.format("UPDATE `nhahang`.`nhanvien` SET `tendangnhap` = NULL WHERE (`tendangnhap` = '%s');",tentk);
            System.err.println(querry);
            stmt.executeUpdate(querry0);
            stmt.executeUpdate(querry);
//To remove previously added rows
            con.close();
        }catch(Exception e){ System.out.println(e);}    
    }

    private void themtkng(String tentk, String matkhau, String tenngd) {
        try{  
            Class.forName("com.mysql.cj.jdbc.Driver");  
            Connection con=DriverManager.getConnection(  
            "jdbc:mysql://localhost:3306/nhahang","root",Ql_nhahang.mysqlpass);  
            //here sonoo is database name, root is username and password  
            Statement stmt=con.createStatement();
            
            String querry0 = String.format("SELECT id_nv FROM nhahang.nhanvien where nhanvien.ten_nv = '%s';",tenngd);
            ResultSet rs=stmt.executeQuery(querry0);
            rs.next();
            String idngd = rs.getString(1);
            String querry2 = String.format("UPDATE `nhahang`.`nhanvien` SET `tendangnhap` = '%s' WHERE (`id_nv` = '%s');", tentk, idngd);
            String querry1 = String.format("INSERT INTO `nhahang`.`login` (`tendangnhap`, `matkhau`) VALUES ('%s', '%s');",tentk, matkhau);
            
            stmt.executeUpdate(querry1);
            stmt.executeUpdate(querry2);
//To remove previously added rows
            con.close();
        }catch(Exception e){ System.out.println(e);}
    }

    private void lammoitbphanquyen() {
        try{  
            Class.forName("com.mysql.cj.jdbc.Driver");  
            Connection con=DriverManager.getConnection(  
            "jdbc:mysql://localhost:3306/nhahang","root",Ql_nhahang.mysqlpass);  
            //here sonoo is database name, root is username and password  
            Statement stmt=con.createStatement();  
            ResultSet rs=stmt.executeQuery("SELECT distinct login.tendangnhap, login.matkhau, nhanvien.ten_nv FROM nhahang.login join nhahang.nhanvien where nhanvien.tendangnhap = login.tendangnhap;");
            DefaultTableModel model = (DefaultTableModel) jTable6.getModel();
            model.setRowCount(0);
            //int cout = 0;
            while(rs.next()){
                //System.out.println(rs.getInt(1)+"\t"+rs.getString(2)+"\t"+rs.getString(3)+"\t"+rs.getInt(4)+"\t"+rs.getInt(5));
                model.addRow(new Object[]{rs.getString(1),rs.getString(2), rs.getString(3)});
                //cout = cout + 1;
            }
            //jLabel18.setText("Tổng số: " + String.valueOf(cout));
        //To remove previously added rows

            con.close();
        }catch(Exception e){ System.out.println(e);}
    }

    private void lammoingsd() {
    try{  
        Class.forName("com.mysql.cj.jdbc.Driver");  
        Connection con=DriverManager.getConnection(  
        "jdbc:mysql://localhost:3306/nhahang","root",Ql_nhahang.mysqlpass);  
        //here sonoo is database name, root is username and password  
        Statement stmt=con.createStatement();  
        ResultSet rs=stmt.executeQuery("SELECT ten_nv , tendangnhap FROM nhahang.nhanvien where tendangnhap is NULL;");
        DefaultComboBoxModel model = (DefaultComboBoxModel) jComboBox4.getModel();
        //int cout = 0;
        model.removeAllElements();
        while(rs.next()){
            model.addElement(rs.getString(1));
        }
        con.close();
    }catch(Exception e){ System.out.println(e);}
    }

    private void xoanv(String idnv) {
        try{  
            Class.forName("com.mysql.cj.jdbc.Driver");  
            Connection con=DriverManager.getConnection(  
            "jdbc:mysql://localhost:3306/nhahang","root",Ql_nhahang.mysqlpass);  
            //here sonoo is database name, root is username and password  
            Statement stmt=con.createStatement();
            String querry = String.format("DELETE FROM `nhahang`.`nhanvien` WHERE (`id_nv` = '%s');",idnv);
            System.err.println(querry);
            stmt.executeUpdate(querry);
//To remove previously added rows
            con.close();
        }catch(Exception e){ System.out.println(e);}
    }
    
}
